# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:16 # Or your desired PostgreSQL version
    environment:
      - POSTGRES_DB=odoo_db
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    build: . # Build from the Dockerfile in the current directory
    ports:
      - "8069:8069" # Odoo web interface
    environment:
      - HOST=localhost
      - USER=nubuserp
      - PASSWORD=Nubus3rp#001$
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo

volumes:
  odoo-db-data:
  odoo-web-data:
