name: Pylint Odoo

on:
  push:
      branches:
        - main
        - "18.0"
  workflow_dispatch:
jobs:
  Builds:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # Setup python #
      - name: Set Up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          
      - name: Listar directorios
        run: ls -l

      - name: Version SO
        run: cat /etc/os-release
