name: Pylint Odoo

on:
  push:
      branches:
        - main
        - "18.0"
  workflow_dispatch:
jobs:
  Builds:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      # Setup python #
      - name: Set Up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install pre-commit-vauxoo
        run: pip install pre-commit-vauxoo

      - name: Run pre-commit-vauxoo checks
        run: pre-commit-vauxoo -t all # Or specify your desired pre-commit-vauxoo arguments
            
      - name: Listar directorios
        run: ls -l

      - name: Version SO
        run: cat /etc/os-releasebuild-and-push

  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: "jruvalcaba@nubuserp.com"
          password: "dckr_pat_UG69kz0EwfryzQjkltGpOfGC3fQ"

      - name: Construir y empujar la imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nubuserp/odoo:latest # Reemplaza con tus datos

  #deploy:
  #  needs: build-and-push # Este job depende del anterior
  #  runs-on: ubuntu-lastest
  #  steps:
  #    - name: Desplegar en Azure App Service
  #      uses: azure/webapps-deploy@v2
  #      with:
  #        app-name: tu-nombre-de-app-azure # Reemplaza con el nombre de tu App Service
  #        slot-name: production # O el nombre de tu slot de despliegue
  #        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  #        images: tu-usuario/tu-imagen:latest
