name: Pylint Odoo

on:
  push:
      branches:
        - main
        - "18.0"
  workflow_dispatch:
jobs:
  Builds:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      # Setup python #
      - name: Set Up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install pre-commit-vauxoo
        run: pip install pre-commit-vauxoo

      - name: Run pre-commit-vauxoo checks
        run: pre-commit-vauxoo -t all # Or specify your desired pre-commit-vauxoo arguments
            
      - name: Listar directorios
        run: ls -l

      - name: Version SO
        run: cat /etc/os-release
